/* tslint:disable */
/* eslint-disable */
/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RepositorySearchDto
 */
export interface RepositorySearchDto {
    /**
     * 
     * @type {number}
     * @memberof RepositorySearchDto
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof RepositorySearchDto
     */
    page?: number;
    /**
     * 
     * @type {string}
     * @memberof RepositorySearchDto
     */
    name?: string;
}
