version: "3.5"

services:
  nestjs:
    build:
      context: ./nestjs
      dockerfile: Dockerfile.dev
    env_file:
     - ./nestjs/.env.dev
    ports:
      - 3001:3001
    volumes:
      - ./nestjs/src/:/app/src

  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: example
    ports:
     - 5432:5432

  redis:
    image: redis:6.2-rc1
    environment:
      REDIS_PASSWORD: password

  redis_commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis
  adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
