/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AuthDto} from './model/AuthDto';
import {CompetenceCreationDto} from './model/CompetenceCreationDto';
import {CompetenceDto} from './model/CompetenceDto';
import {CompetenceListDto} from './model/CompetenceListDto';
import {LearningObjectCreationDto} from './model/LearningObjectCreationDto';
import {LearningObjectDto} from './model/LearningObjectDto';
import {LearningObjectGroupCreationDto} from './model/LearningObjectGroupCreationDto';
import {LearningObjectGroupDto} from './model/LearningObjectGroupDto';
import {LearningObjectModificationDto} from './model/LearningObjectModificationDto';
import {LoGoalCreationDto} from './model/LoGoalCreationDto';
import {LoGoalDto} from './model/LoGoalDto';
import {LoRepositoryCreationDto} from './model/LoRepositoryCreationDto';
import {LoRepositoryDto} from './model/LoRepositoryDto';
import {LoRepositoryListDto} from './model/LoRepositoryListDto';
import {LoRepositoryModifyDto} from './model/LoRepositoryModifyDto';
import {LoginAckDto} from './model/LoginAckDto';
import {LoginDto} from './model/LoginDto';
import {RepositoryCreationDto} from './model/RepositoryCreationDto';
import {RepositoryDto} from './model/RepositoryDto';
import {RepositoryListDto} from './model/RepositoryListDto';
import {RepositorySearchDto} from './model/RepositorySearchDto';
import {ResolvedRepositoryDto} from './model/ResolvedRepositoryDto';
import {ResolvedUeberCompetenceDto} from './model/ResolvedUeberCompetenceDto';
import {ShallowLoRepositoryDto} from './model/ShallowLoRepositoryDto';
import {UberCompetenceResolveRequestDto} from './model/UberCompetenceResolveRequestDto';
import {UeberCompetenceCreationDto} from './model/UeberCompetenceCreationDto';
import {UeberCompetenceModificationDto} from './model/UeberCompetenceModificationDto';
import {UnResolvedUeberCompetenceDto} from './model/UnResolvedUeberCompetenceDto';
import {UnresolvedRepositoryDto} from './model/UnresolvedRepositoryDto';
import {AuthenticationApi} from './api/AuthenticationApi';
import {CompetenciesApi} from './api/CompetenciesApi';
import {LearningObjectsApi} from './api/LearningObjectsApi';

/**
* The_API_description_of_the_Competence_Repository_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CompetenceRepositoryApi = require('index'); // See note below*.
* var xxxSvc = new CompetenceRepositoryApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CompetenceRepositoryApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CompetenceRepositoryApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CompetenceRepositoryApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.3.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthDto model constructor.
     * @property {module:model/AuthDto}
     */
    AuthDto,

    /**
     * The CompetenceCreationDto model constructor.
     * @property {module:model/CompetenceCreationDto}
     */
    CompetenceCreationDto,

    /**
     * The CompetenceDto model constructor.
     * @property {module:model/CompetenceDto}
     */
    CompetenceDto,

    /**
     * The CompetenceListDto model constructor.
     * @property {module:model/CompetenceListDto}
     */
    CompetenceListDto,

    /**
     * The LearningObjectCreationDto model constructor.
     * @property {module:model/LearningObjectCreationDto}
     */
    LearningObjectCreationDto,

    /**
     * The LearningObjectDto model constructor.
     * @property {module:model/LearningObjectDto}
     */
    LearningObjectDto,

    /**
     * The LearningObjectGroupCreationDto model constructor.
     * @property {module:model/LearningObjectGroupCreationDto}
     */
    LearningObjectGroupCreationDto,

    /**
     * The LearningObjectGroupDto model constructor.
     * @property {module:model/LearningObjectGroupDto}
     */
    LearningObjectGroupDto,

    /**
     * The LearningObjectModificationDto model constructor.
     * @property {module:model/LearningObjectModificationDto}
     */
    LearningObjectModificationDto,

    /**
     * The LoGoalCreationDto model constructor.
     * @property {module:model/LoGoalCreationDto}
     */
    LoGoalCreationDto,

    /**
     * The LoGoalDto model constructor.
     * @property {module:model/LoGoalDto}
     */
    LoGoalDto,

    /**
     * The LoRepositoryCreationDto model constructor.
     * @property {module:model/LoRepositoryCreationDto}
     */
    LoRepositoryCreationDto,

    /**
     * The LoRepositoryDto model constructor.
     * @property {module:model/LoRepositoryDto}
     */
    LoRepositoryDto,

    /**
     * The LoRepositoryListDto model constructor.
     * @property {module:model/LoRepositoryListDto}
     */
    LoRepositoryListDto,

    /**
     * The LoRepositoryModifyDto model constructor.
     * @property {module:model/LoRepositoryModifyDto}
     */
    LoRepositoryModifyDto,

    /**
     * The LoginAckDto model constructor.
     * @property {module:model/LoginAckDto}
     */
    LoginAckDto,

    /**
     * The LoginDto model constructor.
     * @property {module:model/LoginDto}
     */
    LoginDto,

    /**
     * The RepositoryCreationDto model constructor.
     * @property {module:model/RepositoryCreationDto}
     */
    RepositoryCreationDto,

    /**
     * The RepositoryDto model constructor.
     * @property {module:model/RepositoryDto}
     */
    RepositoryDto,

    /**
     * The RepositoryListDto model constructor.
     * @property {module:model/RepositoryListDto}
     */
    RepositoryListDto,

    /**
     * The RepositorySearchDto model constructor.
     * @property {module:model/RepositorySearchDto}
     */
    RepositorySearchDto,

    /**
     * The ResolvedRepositoryDto model constructor.
     * @property {module:model/ResolvedRepositoryDto}
     */
    ResolvedRepositoryDto,

    /**
     * The ResolvedUeberCompetenceDto model constructor.
     * @property {module:model/ResolvedUeberCompetenceDto}
     */
    ResolvedUeberCompetenceDto,

    /**
     * The ShallowLoRepositoryDto model constructor.
     * @property {module:model/ShallowLoRepositoryDto}
     */
    ShallowLoRepositoryDto,

    /**
     * The UberCompetenceResolveRequestDto model constructor.
     * @property {module:model/UberCompetenceResolveRequestDto}
     */
    UberCompetenceResolveRequestDto,

    /**
     * The UeberCompetenceCreationDto model constructor.
     * @property {module:model/UeberCompetenceCreationDto}
     */
    UeberCompetenceCreationDto,

    /**
     * The UeberCompetenceModificationDto model constructor.
     * @property {module:model/UeberCompetenceModificationDto}
     */
    UeberCompetenceModificationDto,

    /**
     * The UnResolvedUeberCompetenceDto model constructor.
     * @property {module:model/UnResolvedUeberCompetenceDto}
     */
    UnResolvedUeberCompetenceDto,

    /**
     * The UnresolvedRepositoryDto model constructor.
     * @property {module:model/UnresolvedRepositoryDto}
     */
    UnresolvedRepositoryDto,

    /**
    * The AuthenticationApi service constructor.
    * @property {module:api/AuthenticationApi}
    */
    AuthenticationApi,

    /**
    * The CompetenciesApi service constructor.
    * @property {module:api/CompetenciesApi}
    */
    CompetenciesApi,

    /**
    * The LearningObjectsApi service constructor.
    * @property {module:api/LearningObjectsApi}
    */
    LearningObjectsApi
};
