/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AuthDto model module.
 * @module model/AuthDto
 * @version 0.3.2
 */
export class AuthDto {
  /**
   * Constructs a new <code>AuthDto</code>.
   * @alias module:model/AuthDto
   * @class
   * @param email {String} 
   * @param name {String} 
   * @param password {String} 
   */
  constructor(email, name, password) {
    this.email = email;
    this.name = name;
    this.password = password;
  }

  /**
   * Constructs a <code>AuthDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthDto} obj Optional instance to populate.
   * @return {module:model/AuthDto} The populated <code>AuthDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthDto();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
AuthDto.prototype.email = undefined;

/**
 * @member {String} name
 */
AuthDto.prototype.name = undefined;

/**
 * @member {String} password
 */
AuthDto.prototype.password = undefined;

