/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CompetenceDto model module.
 * @module model/CompetenceDto
 * @version 0.3.2
 */
export class CompetenceDto {
  /**
   * Constructs a new <code>CompetenceDto</code>.
   * @alias module:model/CompetenceDto
   * @class
   * @param id {String} 
   * @param skill {String} 
   * @param level {Number} 
   */
  constructor(id, skill, level) {
    this.id = id;
    this.skill = skill;
    this.level = level;
  }

  /**
   * Constructs a <code>CompetenceDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompetenceDto} obj Optional instance to populate.
   * @return {module:model/CompetenceDto} The populated <code>CompetenceDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CompetenceDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('skill'))
        obj.skill = ApiClient.convertToType(data['skill'], 'String');
      if (data.hasOwnProperty('level'))
        obj.level = ApiClient.convertToType(data['level'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
CompetenceDto.prototype.id = undefined;

/**
 * @member {String} skill
 */
CompetenceDto.prototype.skill = undefined;

/**
 * @member {Number} level
 */
CompetenceDto.prototype.level = undefined;

/**
 * @member {String} description
 */
CompetenceDto.prototype.description = undefined;

