/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CompetenceDto} from './CompetenceDto';

/**
 * The CompetenceListDto model module.
 * @module model/CompetenceListDto
 * @version 0.3.2
 */
export class CompetenceListDto {
  /**
   * Constructs a new <code>CompetenceListDto</code>.
   * @alias module:model/CompetenceListDto
   * @class
   * @param competencies {Array.<module:model/CompetenceDto>} 
   */
  constructor(competencies) {
    this.competencies = competencies;
  }

  /**
   * Constructs a <code>CompetenceListDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompetenceListDto} obj Optional instance to populate.
   * @return {module:model/CompetenceListDto} The populated <code>CompetenceListDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CompetenceListDto();
      if (data.hasOwnProperty('competencies'))
        obj.competencies = ApiClient.convertToType(data['competencies'], [CompetenceDto]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/CompetenceDto>} competencies
 */
CompetenceListDto.prototype.competencies = undefined;

