/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LearningObjectModificationDto model module.
 * @module model/LearningObjectModificationDto
 * @version 0.3.2
 */
export class LearningObjectModificationDto {
  /**
   * Constructs a new <code>LearningObjectModificationDto</code>.
   * @alias module:model/LearningObjectModificationDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LearningObjectModificationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LearningObjectModificationDto} obj Optional instance to populate.
   * @return {module:model/LearningObjectModificationDto} The populated <code>LearningObjectModificationDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LearningObjectModificationDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('requiredCompetencies'))
        obj.requiredCompetencies = ApiClient.convertToType(data['requiredCompetencies'], ['String']);
      if (data.hasOwnProperty('requiredUeberCompetencies'))
        obj.requiredUeberCompetencies = ApiClient.convertToType(data['requiredUeberCompetencies'], ['String']);
      if (data.hasOwnProperty('offeredCompetencies'))
        obj.offeredCompetencies = ApiClient.convertToType(data['offeredCompetencies'], ['String']);
      if (data.hasOwnProperty('offeredUeberCompetencies'))
        obj.offeredUeberCompetencies = ApiClient.convertToType(data['offeredUeberCompetencies'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
LearningObjectModificationDto.prototype.name = undefined;

/**
 * @member {String} description
 */
LearningObjectModificationDto.prototype.description = undefined;

/**
 * @member {Array.<String>} requiredCompetencies
 */
LearningObjectModificationDto.prototype.requiredCompetencies = undefined;

/**
 * @member {Array.<String>} requiredUeberCompetencies
 */
LearningObjectModificationDto.prototype.requiredUeberCompetencies = undefined;

/**
 * @member {Array.<String>} offeredCompetencies
 */
LearningObjectModificationDto.prototype.offeredCompetencies = undefined;

/**
 * @member {Array.<String>} offeredUeberCompetencies
 */
LearningObjectModificationDto.prototype.offeredUeberCompetencies = undefined;

