/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {LearningObjectDto} from './LearningObjectDto';

/**
 * The LearningObjectGroupDto model module.
 * @module model/LearningObjectGroupDto
 * @version 0.3.2
 */
export class LearningObjectGroupDto {
  /**
   * Constructs a new <code>LearningObjectGroupDto</code>.
   * @alias module:model/LearningObjectGroupDto
   * @class
   * @param id {String} 
   * @param repositoryId {String} 
   * @param name {String} 
   * @param nestedLearningObjects {Array.<module:model/LearningObjectDto>} 
   * @param nestedGroups {Array.<module:model/LearningObjectGroupDto>} 
   */
  constructor(id, repositoryId, name, nestedLearningObjects, nestedGroups) {
    this.id = id;
    this.repositoryId = repositoryId;
    this.name = name;
    this.nestedLearningObjects = nestedLearningObjects;
    this.nestedGroups = nestedGroups;
  }

  /**
   * Constructs a <code>LearningObjectGroupDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LearningObjectGroupDto} obj Optional instance to populate.
   * @return {module:model/LearningObjectGroupDto} The populated <code>LearningObjectGroupDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LearningObjectGroupDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('repositoryId'))
        obj.repositoryId = ApiClient.convertToType(data['repositoryId'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('nestedLearningObjects'))
        obj.nestedLearningObjects = ApiClient.convertToType(data['nestedLearningObjects'], [LearningObjectDto]);
      if (data.hasOwnProperty('nestedGroups'))
        obj.nestedGroups = ApiClient.convertToType(data['nestedGroups'], [LearningObjectGroupDto]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
LearningObjectGroupDto.prototype.id = undefined;

/**
 * @member {String} repositoryId
 */
LearningObjectGroupDto.prototype.repositoryId = undefined;

/**
 * @member {String} name
 */
LearningObjectGroupDto.prototype.name = undefined;

/**
 * @member {String} description
 */
LearningObjectGroupDto.prototype.description = undefined;

/**
 * @member {Array.<module:model/LearningObjectDto>} nestedLearningObjects
 */
LearningObjectGroupDto.prototype.nestedLearningObjects = undefined;

/**
 * @member {Array.<module:model/LearningObjectGroupDto>} nestedGroups
 */
LearningObjectGroupDto.prototype.nestedGroups = undefined;

