/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LearningObjectGroupCreationDto model module.
 * @module model/LearningObjectGroupCreationDto
 * @version 0.3.2
 */
export class LearningObjectGroupCreationDto {
  /**
   * Constructs a new <code>LearningObjectGroupCreationDto</code>.
   * @alias module:model/LearningObjectGroupCreationDto
   * @class
   * @param repositoryId {String} 
   * @param name {String} 
   */
  constructor(repositoryId, name) {
    this.repositoryId = repositoryId;
    this.name = name;
  }

  /**
   * Constructs a <code>LearningObjectGroupCreationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LearningObjectGroupCreationDto} obj Optional instance to populate.
   * @return {module:model/LearningObjectGroupCreationDto} The populated <code>LearningObjectGroupCreationDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LearningObjectGroupCreationDto();
      if (data.hasOwnProperty('repositoryId'))
        obj.repositoryId = ApiClient.convertToType(data['repositoryId'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('nestedLearningObjects'))
        obj.nestedLearningObjects = ApiClient.convertToType(data['nestedLearningObjects'], ['String']);
      if (data.hasOwnProperty('nestedGroups'))
        obj.nestedGroups = ApiClient.convertToType(data['nestedGroups'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} repositoryId
 */
LearningObjectGroupCreationDto.prototype.repositoryId = undefined;

/**
 * @member {String} name
 */
LearningObjectGroupCreationDto.prototype.name = undefined;

/**
 * @member {String} description
 */
LearningObjectGroupCreationDto.prototype.description = undefined;

/**
 * @member {Array.<String>} nestedLearningObjects
 */
LearningObjectGroupCreationDto.prototype.nestedLearningObjects = undefined;

/**
 * @member {Array.<String>} nestedGroups
 */
LearningObjectGroupCreationDto.prototype.nestedGroups = undefined;

