/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LoginAckDto model module.
 * @module model/LoginAckDto
 * @version 0.3.2
 */
export class LoginAckDto {
  /**
   * Constructs a new <code>LoginAckDto</code>.
   * @alias module:model/LoginAckDto
   * @class
   * @param access_token {String} 
   * @param id {String} 
   * @param email {String} 
   * @param name {String} 
   */
  constructor(access_token, id, email, name) {
    this.access_token = access_token;
    this.id = id;
    this.email = email;
    this.name = name;
  }

  /**
   * Constructs a <code>LoginAckDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginAckDto} obj Optional instance to populate.
   * @return {module:model/LoginAckDto} The populated <code>LoginAckDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoginAckDto();
      if (data.hasOwnProperty('access_token'))
        obj.access_token = ApiClient.convertToType(data['access_token'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} access_token
 */
LoginAckDto.prototype.access_token = undefined;

/**
 * @member {String} id
 */
LoginAckDto.prototype.id = undefined;

/**
 * @member {String} email
 */
LoginAckDto.prototype.email = undefined;

/**
 * @member {String} name
 */
LoginAckDto.prototype.name = undefined;

