/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LoGoalCreationDto model module.
 * @module model/LoGoalCreationDto
 * @version 0.3.2
 */
export class LoGoalCreationDto {
  /**
   * Constructs a new <code>LoGoalCreationDto</code>.
   * @alias module:model/LoGoalCreationDto
   * @class
   * @param name {String} 
   * @param competencies {Array.<String>} 
   * @param uberCompetencies {Array.<String>} 
   */
  constructor(name, competencies, uberCompetencies) {
    this.name = name;
    this.competencies = competencies;
    this.uberCompetencies = uberCompetencies;
  }

  /**
   * Constructs a <code>LoGoalCreationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoGoalCreationDto} obj Optional instance to populate.
   * @return {module:model/LoGoalCreationDto} The populated <code>LoGoalCreationDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoGoalCreationDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('competencies'))
        obj.competencies = ApiClient.convertToType(data['competencies'], ['String']);
      if (data.hasOwnProperty('uberCompetencies'))
        obj.uberCompetencies = ApiClient.convertToType(data['uberCompetencies'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
LoGoalCreationDto.prototype.name = undefined;

/**
 * @member {String} description
 */
LoGoalCreationDto.prototype.description = undefined;

/**
 * @member {Array.<String>} competencies
 */
LoGoalCreationDto.prototype.competencies = undefined;

/**
 * @member {Array.<String>} uberCompetencies
 */
LoGoalCreationDto.prototype.uberCompetencies = undefined;

