/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ShallowLoRepositoryDto} from './ShallowLoRepositoryDto';

/**
 * The LoRepositoryListDto model module.
 * @module model/LoRepositoryListDto
 * @version 0.3.2
 */
export class LoRepositoryListDto {
  /**
   * Constructs a new <code>LoRepositoryListDto</code>.
   * @alias module:model/LoRepositoryListDto
   * @class
   * @param repositories {Array.<module:model/ShallowLoRepositoryDto>} 
   */
  constructor(repositories) {
    this.repositories = repositories;
  }

  /**
   * Constructs a <code>LoRepositoryListDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoRepositoryListDto} obj Optional instance to populate.
   * @return {module:model/LoRepositoryListDto} The populated <code>LoRepositoryListDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoRepositoryListDto();
      if (data.hasOwnProperty('repositories'))
        obj.repositories = ApiClient.convertToType(data['repositories'], [ShallowLoRepositoryDto]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ShallowLoRepositoryDto>} repositories
 */
LoRepositoryListDto.prototype.repositories = undefined;

