/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LoRepositoryCreationDto model module.
 * @module model/LoRepositoryCreationDto
 * @version 0.3.2
 */
export class LoRepositoryCreationDto {
  /**
   * Constructs a new <code>LoRepositoryCreationDto</code>.
   * @alias module:model/LoRepositoryCreationDto
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>LoRepositoryCreationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoRepositoryCreationDto} obj Optional instance to populate.
   * @return {module:model/LoRepositoryCreationDto} The populated <code>LoRepositoryCreationDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoRepositoryCreationDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
LoRepositoryCreationDto.prototype.name = undefined;

/**
 * @member {String} description
 */
LoRepositoryCreationDto.prototype.description = undefined;

