/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LoRepositoryModifyDto model module.
 * @module model/LoRepositoryModifyDto
 * @version 0.3.2
 */
export class LoRepositoryModifyDto {
  /**
   * Constructs a new <code>LoRepositoryModifyDto</code>.
   * @alias module:model/LoRepositoryModifyDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LoRepositoryModifyDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoRepositoryModifyDto} obj Optional instance to populate.
   * @return {module:model/LoRepositoryModifyDto} The populated <code>LoRepositoryModifyDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoRepositoryModifyDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
LoRepositoryModifyDto.prototype.name = undefined;

/**
 * @member {String} description
 */
LoRepositoryModifyDto.prototype.description = undefined;

