/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RepositorySearchDto model module.
 * @module model/RepositorySearchDto
 * @version 0.3.2
 */
export class RepositorySearchDto {
  /**
   * Constructs a new <code>RepositorySearchDto</code>.
   * @alias module:model/RepositorySearchDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RepositorySearchDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RepositorySearchDto} obj Optional instance to populate.
   * @return {module:model/RepositorySearchDto} The populated <code>RepositorySearchDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RepositorySearchDto();
      if (data.hasOwnProperty('pageSize'))
        obj.pageSize = ApiClient.convertToType(data['pageSize'], 'Number');
      if (data.hasOwnProperty('page'))
        obj.page = ApiClient.convertToType(data['page'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} pageSize
 */
RepositorySearchDto.prototype.pageSize = undefined;

/**
 * @member {Number} page
 */
RepositorySearchDto.prototype.page = undefined;

/**
 * @member {String} name
 */
RepositorySearchDto.prototype.name = undefined;

