/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RepositoryDto model module.
 * @module model/RepositoryDto
 * @version 0.3.2
 */
export class RepositoryDto {
  /**
   * Constructs a new <code>RepositoryDto</code>.
   * @alias module:model/RepositoryDto
   * @class
   * @param userId {String} 
   * @param id {String} 
   * @param name {String} 
   */
  constructor(userId, id, name) {
    this.userId = userId;
    this.id = id;
    this.name = name;
  }

  /**
   * Constructs a <code>RepositoryDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RepositoryDto} obj Optional instance to populate.
   * @return {module:model/RepositoryDto} The populated <code>RepositoryDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RepositoryDto();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('taxonomy'))
        obj.taxonomy = ApiClient.convertToType(data['taxonomy'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
RepositoryDto.prototype.userId = undefined;

/**
 * @member {String} id
 */
RepositoryDto.prototype.id = undefined;

/**
 * @member {String} taxonomy
 */
RepositoryDto.prototype.taxonomy = undefined;

/**
 * @member {String} description
 */
RepositoryDto.prototype.description = undefined;

/**
 * @member {String} name
 */
RepositoryDto.prototype.name = undefined;

/**
 * @member {String} version
 */
RepositoryDto.prototype.version = undefined;

