/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CompetenceDto} from './CompetenceDto';

/**
 * The ResolvedUeberCompetenceDto model module.
 * @module model/ResolvedUeberCompetenceDto
 * @version 0.3.2
 */
export class ResolvedUeberCompetenceDto {
  /**
   * Constructs a new <code>ResolvedUeberCompetenceDto</code>.
   * @alias module:model/ResolvedUeberCompetenceDto
   * @class
   * @param id {String} 
   * @param name {String} 
   * @param nestedCompetencies {Array.<module:model/CompetenceDto>} 
   * @param nestedUeberCompetencies {Array.<module:model/ResolvedUeberCompetenceDto>} 
   */
  constructor(id, name, nestedCompetencies, nestedUeberCompetencies) {
    this.id = id;
    this.name = name;
    this.nestedCompetencies = nestedCompetencies;
    this.nestedUeberCompetencies = nestedUeberCompetencies;
  }

  /**
   * Constructs a <code>ResolvedUeberCompetenceDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResolvedUeberCompetenceDto} obj Optional instance to populate.
   * @return {module:model/ResolvedUeberCompetenceDto} The populated <code>ResolvedUeberCompetenceDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResolvedUeberCompetenceDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('nestedCompetencies'))
        obj.nestedCompetencies = ApiClient.convertToType(data['nestedCompetencies'], [CompetenceDto]);
      if (data.hasOwnProperty('nestedUeberCompetencies'))
        obj.nestedUeberCompetencies = ApiClient.convertToType(data['nestedUeberCompetencies'], [ResolvedUeberCompetenceDto]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ResolvedUeberCompetenceDto.prototype.id = undefined;

/**
 * @member {String} name
 */
ResolvedUeberCompetenceDto.prototype.name = undefined;

/**
 * @member {String} description
 */
ResolvedUeberCompetenceDto.prototype.description = undefined;

/**
 * @member {Array.<module:model/CompetenceDto>} nestedCompetencies
 */
ResolvedUeberCompetenceDto.prototype.nestedCompetencies = undefined;

/**
 * @member {Array.<module:model/ResolvedUeberCompetenceDto>} nestedUeberCompetencies
 */
ResolvedUeberCompetenceDto.prototype.nestedUeberCompetencies = undefined;

