/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UberCompetenceResolveRequestDto model module.
 * @module model/UberCompetenceResolveRequestDto
 * @version 0.3.2
 */
export class UberCompetenceResolveRequestDto {
  /**
   * Constructs a new <code>UberCompetenceResolveRequestDto</code>.
   * @alias module:model/UberCompetenceResolveRequestDto
   * @class
   * @param uberCompetencies {Array.<String>} 
   */
  constructor(uberCompetencies) {
    this.uberCompetencies = uberCompetencies;
  }

  /**
   * Constructs a <code>UberCompetenceResolveRequestDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UberCompetenceResolveRequestDto} obj Optional instance to populate.
   * @return {module:model/UberCompetenceResolveRequestDto} The populated <code>UberCompetenceResolveRequestDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UberCompetenceResolveRequestDto();
      if (data.hasOwnProperty('uberCompetencies'))
        obj.uberCompetencies = ApiClient.convertToType(data['uberCompetencies'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} uberCompetencies
 */
UberCompetenceResolveRequestDto.prototype.uberCompetencies = undefined;

