/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UeberCompetenceModificationDto model module.
 * @module model/UeberCompetenceModificationDto
 * @version 0.3.2
 */
export class UeberCompetenceModificationDto {
  /**
   * Constructs a new <code>UeberCompetenceModificationDto</code>.
   * @alias module:model/UeberCompetenceModificationDto
   * @class
   * @param ueberCompetenceId {String} 
   * @param nestedCompetencies {Array.<String>} 
   * @param nestedUeberCompetencies {Array.<String>} 
   */
  constructor(ueberCompetenceId, nestedCompetencies, nestedUeberCompetencies) {
    this.ueberCompetenceId = ueberCompetenceId;
    this.nestedCompetencies = nestedCompetencies;
    this.nestedUeberCompetencies = nestedUeberCompetencies;
  }

  /**
   * Constructs a <code>UeberCompetenceModificationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UeberCompetenceModificationDto} obj Optional instance to populate.
   * @return {module:model/UeberCompetenceModificationDto} The populated <code>UeberCompetenceModificationDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UeberCompetenceModificationDto();
      if (data.hasOwnProperty('ueberCompetenceId'))
        obj.ueberCompetenceId = ApiClient.convertToType(data['ueberCompetenceId'], 'String');
      if (data.hasOwnProperty('nestedCompetencies'))
        obj.nestedCompetencies = ApiClient.convertToType(data['nestedCompetencies'], ['String']);
      if (data.hasOwnProperty('nestedUeberCompetencies'))
        obj.nestedUeberCompetencies = ApiClient.convertToType(data['nestedUeberCompetencies'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} ueberCompetenceId
 */
UeberCompetenceModificationDto.prototype.ueberCompetenceId = undefined;

/**
 * @member {Array.<String>} nestedCompetencies
 */
UeberCompetenceModificationDto.prototype.nestedCompetencies = undefined;

/**
 * @member {Array.<String>} nestedUeberCompetencies
 */
UeberCompetenceModificationDto.prototype.nestedUeberCompetencies = undefined;

