/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UnResolvedUeberCompetenceDto model module.
 * @module model/UnResolvedUeberCompetenceDto
 * @version 0.3.2
 */
export class UnResolvedUeberCompetenceDto {
  /**
   * Constructs a new <code>UnResolvedUeberCompetenceDto</code>.
   * @alias module:model/UnResolvedUeberCompetenceDto
   * @class
   * @param name {String} 
   * @param id {String} 
   * @param parents {Array.<String>} 
   */
  constructor(name, id, parents) {
    this.name = name;
    this.id = id;
    this.parents = parents;
  }

  /**
   * Constructs a <code>UnResolvedUeberCompetenceDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnResolvedUeberCompetenceDto} obj Optional instance to populate.
   * @return {module:model/UnResolvedUeberCompetenceDto} The populated <code>UnResolvedUeberCompetenceDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UnResolvedUeberCompetenceDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('nestedCompetencies'))
        obj.nestedCompetencies = ApiClient.convertToType(data['nestedCompetencies'], ['String']);
      if (data.hasOwnProperty('nestedUeberCompetencies'))
        obj.nestedUeberCompetencies = ApiClient.convertToType(data['nestedUeberCompetencies'], ['String']);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('parents'))
        obj.parents = ApiClient.convertToType(data['parents'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
UnResolvedUeberCompetenceDto.prototype.name = undefined;

/**
 * @member {String} description
 */
UnResolvedUeberCompetenceDto.prototype.description = undefined;

/**
 * @member {Array.<String>} nestedCompetencies
 */
UnResolvedUeberCompetenceDto.prototype.nestedCompetencies = undefined;

/**
 * @member {Array.<String>} nestedUeberCompetencies
 */
UnResolvedUeberCompetenceDto.prototype.nestedUeberCompetencies = undefined;

/**
 * @member {String} id
 */
UnResolvedUeberCompetenceDto.prototype.id = undefined;

/**
 * @member {Array.<String>} parents
 */
UnResolvedUeberCompetenceDto.prototype.parents = undefined;

