/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UnresolvedRepositoryDto model module.
 * @module model/UnresolvedRepositoryDto
 * @version 0.3.2
 */
export class UnresolvedRepositoryDto {
  /**
   * Constructs a new <code>UnresolvedRepositoryDto</code>.
   * @alias module:model/UnresolvedRepositoryDto
   * @class
   * @param userId {String} 
   * @param id {String} 
   * @param name {String} 
   * @param competencies {Array.<String>} 
   * @param ueberCompetencies {Array.<String>} 
   */
  constructor(userId, id, name, competencies, ueberCompetencies) {
    this.userId = userId;
    this.id = id;
    this.name = name;
    this.competencies = competencies;
    this.ueberCompetencies = ueberCompetencies;
  }

  /**
   * Constructs a <code>UnresolvedRepositoryDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnresolvedRepositoryDto} obj Optional instance to populate.
   * @return {module:model/UnresolvedRepositoryDto} The populated <code>UnresolvedRepositoryDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UnresolvedRepositoryDto();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('taxonomy'))
        obj.taxonomy = ApiClient.convertToType(data['taxonomy'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
      if (data.hasOwnProperty('competencies'))
        obj.competencies = ApiClient.convertToType(data['competencies'], ['String']);
      if (data.hasOwnProperty('ueberCompetencies'))
        obj.ueberCompetencies = ApiClient.convertToType(data['ueberCompetencies'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
UnresolvedRepositoryDto.prototype.userId = undefined;

/**
 * @member {String} id
 */
UnresolvedRepositoryDto.prototype.id = undefined;

/**
 * @member {String} taxonomy
 */
UnresolvedRepositoryDto.prototype.taxonomy = undefined;

/**
 * @member {String} description
 */
UnresolvedRepositoryDto.prototype.description = undefined;

/**
 * @member {String} name
 */
UnresolvedRepositoryDto.prototype.name = undefined;

/**
 * @member {String} version
 */
UnresolvedRepositoryDto.prototype.version = undefined;

/**
 * @member {Array.<String>} competencies
 */
UnresolvedRepositoryDto.prototype.competencies = undefined;

/**
 * @member {Array.<String>} ueberCompetencies
 */
UnresolvedRepositoryDto.prototype.ueberCompetencies = undefined;

