/* tslint:disable */
/* eslint-disable */
/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LearningObjectDto } from './learning-object-dto';

/**
 * 
 * @export
 * @interface LearningObjectGroupDto
 */
export interface LearningObjectGroupDto {
    /**
     * 
     * @type {string}
     * @memberof LearningObjectGroupDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LearningObjectGroupDto
     */
    repositoryId: string;
    /**
     * 
     * @type {string}
     * @memberof LearningObjectGroupDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LearningObjectGroupDto
     */
    description?: string;
    /**
     * 
     * @type {Array<LearningObjectDto>}
     * @memberof LearningObjectGroupDto
     */
    nestedLearningObjects: Array<LearningObjectDto>;
    /**
     * 
     * @type {Array<LearningObjectGroupDto>}
     * @memberof LearningObjectGroupDto
     */
    nestedGroups: Array<LearningObjectGroupDto>;
}
