/* tslint:disable */
/* eslint-disable */
/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LoginAckDto
 */
export interface LoginAckDto {
    /**
     * 
     * @type {string}
     * @memberof LoginAckDto
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof LoginAckDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LoginAckDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginAckDto
     */
    name: string;
}
