/* tslint:disable */
/* eslint-disable */
/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UnResolvedUeberCompetenceDto
 */
export interface UnResolvedUeberCompetenceDto {
    /**
     * 
     * @type {string}
     * @memberof UnResolvedUeberCompetenceDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UnResolvedUeberCompetenceDto
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UnResolvedUeberCompetenceDto
     */
    nestedCompetencies?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UnResolvedUeberCompetenceDto
     */
    nestedUeberCompetencies?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UnResolvedUeberCompetenceDto
     */
    id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UnResolvedUeberCompetenceDto
     */
    parents: Array<string>;
}
