/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CompetenceRepositoryApi);
  }
}(this, function(expect, CompetenceRepositoryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CompetenceRepositoryApi.AuthenticationApi();
  });

  describe('(package)', function() {
    describe('AuthenticationApi', function() {
      describe('authControllerLogin', function() {
        it('should call authControllerLogin successfully', function(done) {
          // TODO: uncomment, update parameter values for authControllerLogin call and complete the assertions
          /*

          instance.authControllerLogin(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CompetenceRepositoryApi.LoginAckDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('authControllerRegister', function() {
        it('should call authControllerRegister successfully', function(done) {
          // TODO: uncomment, update parameter values for authControllerRegister call and complete the assertions
          /*

          instance.authControllerRegister(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CompetenceRepositoryApi.LoginAckDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
