/* tslint:disable */
/* eslint-disable */
/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LearningObjectModificationDto
 */
export interface LearningObjectModificationDto {
    /**
     * 
     * @type {string}
     * @memberof LearningObjectModificationDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LearningObjectModificationDto
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningObjectModificationDto
     */
    requiredCompetencies?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningObjectModificationDto
     */
    requiredUeberCompetencies?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningObjectModificationDto
     */
    offeredCompetencies?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningObjectModificationDto
     */
    offeredUeberCompetencies?: Array<string>;
}
