/* tslint:disable */
/* eslint-disable */
/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LearningObjectDto } from './learning-object-dto';
import { LearningObjectGroupDto } from './learning-object-group-dto';
import { LoGoalDto } from './lo-goal-dto';
/**
 * 
 * @export
 * @interface LoRepositoryDto
 */
export interface LoRepositoryDto {
    /**
     * 
     * @type {string}
     * @memberof LoRepositoryDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LoRepositoryDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LoRepositoryDto
     */
    owner: string;
    /**
     * 
     * @type {string}
     * @memberof LoRepositoryDto
     */
    description?: string;
    /**
     * 
     * @type {Array<LearningObjectDto>}
     * @memberof LoRepositoryDto
     */
    learningObjects: Array<LearningObjectDto>;
    /**
     * 
     * @type {Array<LearningObjectGroupDto>}
     * @memberof LoRepositoryDto
     */
    learningObjectsGroups: Array<LearningObjectGroupDto>;
    /**
     * 
     * @type {Array<LoGoalDto>}
     * @memberof LoRepositoryDto
     */
    goals: Array<LoGoalDto>;
}
