/* tslint:disable */
/* eslint-disable */
/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RepositoryDto } from './repository-dto';
/**
 * 
 * @export
 * @interface RepositoryListDto
 */
export interface RepositoryListDto {
    /**
     * 
     * @type {Array<RepositoryDto>}
     * @memberof RepositoryListDto
     */
    repositories: Array<RepositoryDto>;
}
