/* tslint:disable */
/* eslint-disable */
/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UnresolvedRepositoryDto
 */
export interface UnresolvedRepositoryDto {
    /**
     * 
     * @type {string}
     * @memberof UnresolvedRepositoryDto
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UnresolvedRepositoryDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UnresolvedRepositoryDto
     */
    taxonomy?: string;
    /**
     * 
     * @type {string}
     * @memberof UnresolvedRepositoryDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UnresolvedRepositoryDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UnresolvedRepositoryDto
     */
    version?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UnresolvedRepositoryDto
     */
    competencies: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UnresolvedRepositoryDto
     */
    ueberCompetencies: Array<string>;
}
