/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * User Service using Flask, OpenAPI and Connexion
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    learningProfileId?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    skillId?: number;
}
