/* tslint:disable */
/* eslint-disable */
/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LearningObjectCreationDto
 */
export interface LearningObjectCreationDto {
    /**
     * 
     * @type {string}
     * @memberof LearningObjectCreationDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LearningObjectCreationDto
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningObjectCreationDto
     */
    requiredCompetencies: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningObjectCreationDto
     */
    requiredUeberCompetencies: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningObjectCreationDto
     */
    offeredCompetencies: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningObjectCreationDto
     */
    offeredUeberCompetencies: Array<string>;
}
