/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LearningObjectDto } from './learningObjectDto';
import { LearningObjectGroupDto } from './learningObjectGroupDto';
import { LoGoalDto } from './loGoalDto';

export interface LoRepositoryDto { 
    id: string;
    name: string;
    owner: string;
    description?: string;
    learningObjects: Array<LearningObjectDto>;
    learningObjectsGroups: Array<LearningObjectGroupDto>;
    goals: Array<LoGoalDto>;
}