/* tslint:disable */
/* eslint-disable */
/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompetenceDto } from './competence-dto';
import { ResolvedUeberCompetenceDto } from './resolved-ueber-competence-dto';
/**
 * 
 * @export
 * @interface ResolvedUeberCompetenceDto
 */
export interface ResolvedUeberCompetenceDto {
    /**
     * 
     * @type {string}
     * @memberof ResolvedUeberCompetenceDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ResolvedUeberCompetenceDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ResolvedUeberCompetenceDto
     */
    description?: string;
    /**
     * 
     * @type {Array<CompetenceDto>}
     * @memberof ResolvedUeberCompetenceDto
     */
    nestedCompetencies: Array<CompetenceDto>;
    /**
     * 
     * @type {Array<ResolvedUeberCompetenceDto>}
     * @memberof ResolvedUeberCompetenceDto
     */
    nestedUeberCompetencies: Array<ResolvedUeberCompetenceDto>;
}
