/* tslint:disable */
/* eslint-disable */
/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ShallowLoRepositoryDto
 */
export interface ShallowLoRepositoryDto {
    /**
     * 
     * @type {string}
     * @memberof ShallowLoRepositoryDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ShallowLoRepositoryDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ShallowLoRepositoryDto
     */
    owner: string;
    /**
     * 
     * @type {string}
     * @memberof ShallowLoRepositoryDto
     */
    description?: string;
}
