/* tslint:disable */
/* eslint-disable */
/**
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompetenceDto } from './competence-dto';
import { ResolvedUeberCompetenceDto } from './resolved-ueber-competence-dto';
/**
 * 
 * @export
 * @interface ResolvedRepositoryDto
 */
export interface ResolvedRepositoryDto {
    /**
     * 
     * @type {string}
     * @memberof ResolvedRepositoryDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ResolvedRepositoryDto
     */
    taxonomy?: string;
    /**
     * 
     * @type {string}
     * @memberof ResolvedRepositoryDto
     */
    description?: string;
    /**
     * 
     * @type {Array<CompetenceDto>}
     * @memberof ResolvedRepositoryDto
     */
    competencies: Array<CompetenceDto>;
    /**
     * 
     * @type {Array<ResolvedUeberCompetenceDto>}
     * @memberof ResolvedRepositoryDto
     */
    ueberCompetencies: Array<ResolvedUeberCompetenceDto>;
    /**
     * 
     * @type {string}
     * @memberof ResolvedRepositoryDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ResolvedRepositoryDto
     */
    version?: string;
}
