/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CompetenceRepositoryApi);
  }
}(this, function(expect, CompetenceRepositoryApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LearningObjectModificationDto', function() {
      beforeEach(function() {
        instance = new CompetenceRepositoryApi.LearningObjectModificationDto();
      });

      it('should create an instance of LearningObjectModificationDto', function() {
        // TODO: update the code to test LearningObjectModificationDto
        expect(instance).to.be.a(CompetenceRepositoryApi.LearningObjectModificationDto);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property requiredCompetencies (base name: "requiredCompetencies")', function() {
        // TODO: update the code to test the property requiredCompetencies
        expect(instance).to.have.property('requiredCompetencies');
        // expect(instance.requiredCompetencies).to.be(expectedValueLiteral);
      });

      it('should have the property requiredUeberCompetencies (base name: "requiredUeberCompetencies")', function() {
        // TODO: update the code to test the property requiredUeberCompetencies
        expect(instance).to.have.property('requiredUeberCompetencies');
        // expect(instance.requiredUeberCompetencies).to.be(expectedValueLiteral);
      });

      it('should have the property offeredCompetencies (base name: "offeredCompetencies")', function() {
        // TODO: update the code to test the property offeredCompetencies
        expect(instance).to.have.property('offeredCompetencies');
        // expect(instance.offeredCompetencies).to.be(expectedValueLiteral);
      });

      it('should have the property offeredUeberCompetencies (base name: "offeredUeberCompetencies")', function() {
        // TODO: update the code to test the property offeredUeberCompetencies
        expect(instance).to.have.property('offeredUeberCompetencies');
        // expect(instance.offeredUeberCompetencies).to.be(expectedValueLiteral);
      });

    });
  });

}));
