/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CompetenceRepositoryApi);
  }
}(this, function(expect, CompetenceRepositoryApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LearningObjectGroupDto', function() {
      beforeEach(function() {
        instance = new CompetenceRepositoryApi.LearningObjectGroupDto();
      });

      it('should create an instance of LearningObjectGroupDto', function() {
        // TODO: update the code to test LearningObjectGroupDto
        expect(instance).to.be.a(CompetenceRepositoryApi.LearningObjectGroupDto);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property repositoryId (base name: "repositoryId")', function() {
        // TODO: update the code to test the property repositoryId
        expect(instance).to.have.property('repositoryId');
        // expect(instance.repositoryId).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property nestedLearningObjects (base name: "nestedLearningObjects")', function() {
        // TODO: update the code to test the property nestedLearningObjects
        expect(instance).to.have.property('nestedLearningObjects');
        // expect(instance.nestedLearningObjects).to.be(expectedValueLiteral);
      });

      it('should have the property nestedGroups (base name: "nestedGroups")', function() {
        // TODO: update the code to test the property nestedGroups
        expect(instance).to.have.property('nestedGroups');
        // expect(instance.nestedGroups).to.be(expectedValueLiteral);
      });

    });
  });

}));
