/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CompetenceRepositoryApi);
  }
}(this, function(expect, CompetenceRepositoryApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UberCompetenceResolveRequestDto', function() {
      beforeEach(function() {
        instance = new CompetenceRepositoryApi.UberCompetenceResolveRequestDto();
      });

      it('should create an instance of UberCompetenceResolveRequestDto', function() {
        // TODO: update the code to test UberCompetenceResolveRequestDto
        expect(instance).to.be.a(CompetenceRepositoryApi.UberCompetenceResolveRequestDto);
      });

      it('should have the property uberCompetencies (base name: "uberCompetencies")', function() {
        // TODO: update the code to test the property uberCompetencies
        expect(instance).to.have.property('uberCompetencies');
        // expect(instance.uberCompetencies).to.be(expectedValueLiteral);
      });

    });
  });

}));
