/*
 * Competence Repository
 * The API description of the Competence Repository.
 *
 * OpenAPI spec version: 0.3.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CompetenceRepositoryApi);
  }
}(this, function(expect, CompetenceRepositoryApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UnresolvedRepositoryDto', function() {
      beforeEach(function() {
        instance = new CompetenceRepositoryApi.UnresolvedRepositoryDto();
      });

      it('should create an instance of UnresolvedRepositoryDto', function() {
        // TODO: update the code to test UnresolvedRepositoryDto
        expect(instance).to.be.a(CompetenceRepositoryApi.UnresolvedRepositoryDto);
      });

      it('should have the property userId (base name: "userId")', function() {
        // TODO: update the code to test the property userId
        expect(instance).to.have.property('userId');
        // expect(instance.userId).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property taxonomy (base name: "taxonomy")', function() {
        // TODO: update the code to test the property taxonomy
        expect(instance).to.have.property('taxonomy');
        // expect(instance.taxonomy).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property version (base name: "version")', function() {
        // TODO: update the code to test the property version
        expect(instance).to.have.property('version');
        // expect(instance.version).to.be(expectedValueLiteral);
      });

      it('should have the property competencies (base name: "competencies")', function() {
        // TODO: update the code to test the property competencies
        expect(instance).to.have.property('competencies');
        // expect(instance.competencies).to.be(expectedValueLiteral);
      });

      it('should have the property ueberCompetencies (base name: "ueberCompetencies")', function() {
        // TODO: update the code to test the property ueberCompetencies
        expect(instance).to.have.property('ueberCompetencies');
        // expect(instance.ueberCompetencies).to.be(expectedValueLiteral);
      });

    });
  });

}));
